import {GroupCategory} from '../../interfaces/categories';
export class Globals{
    categories_dt: GroupCategory []= [
        {
        id:1,
        title:'Vocabulario',
        list: [
            {
                id:1,
                title:'A',
                sing:'',
                isvocal:true,
                est:true
            },
            {
                id:2,
                title:'I',
                sing:'',
                isvocal:true,
                est:true
            },
            {
                id:3,
                title:'U',
                sing:'',
                isvocal:true,
                est:true
            },
            {
                id:4,
                title:'CH',
                sing:'',
                isvocal:false,
                est:true
            },
            {
                id:5,
                title:'H',
                sing:'',
                isvocal:false,
                est:true
            },
            {
                id:6,
                title:'K',
                sing:'',
                isvocal:false,
                est:true
            },
            {
                id:7,
                title:'L',
                sing:'',
                isvocal:false,
                est:true
            },
            {
                id:8,
                title:'LL',
                sing:'',
                isvocal:false,
                est:true
            },
            {
                id:9,
                title:'M',
                sing:'',
                isvocal:false,
                est:true
            },
            {
                id:10,
                title:'N',
                sing:'',
                isvocal:false,
                est:true
            },
            {
                id:11,
                title:'N',
                sing:'',
                isvocal:false,
                est:true
            },
            {
                id:12,
                title:'P',
                sing:'',
                isvocal:false,
                est:true
            }
        ],
        est:true        
        },
        {
            id:2,
            title:'Numeros',
            titlek:'Yupaykuna',
            list: [
                {
                    id:1,
                    title:'uno',
                    titlek:'Shunk',
                    sing:'',
                    est:true
                },
                {
                    id:2,
                    title:'dos',
                    titlek:'Iskay',
                    sing:'',
                    est:true
                },
                {
                    id:3,
                    title:'tres',
                    titlek:'Kimsa',
                    sing:'',
                    est:true
                },   
                {
                    id:4,
                    title:'cuatro',
                    titlek:'Chusku',
                    sing:'',
                    est:true
                },                      
            ],
            est:true        
        },
        {
            id:3,
            title:'Colores',
            titlek:'Tullpukuna',
            list: [
                {
                    id:1,
                    title:'amarrillo',
                    titlek:'Killu',
                    sing:'',
                    est:true
                },               
                {
                    id:2,
                    title:'azul',
                    titlek:'Ankas',
                    sing:'',
                    est:true
                },                
                {
                    id:3,
                    title:'cafe',
                    titlek:'Paku',
                    sing:'',
                    est:true
                },                
            ],
            est:true        
        } 
    ];
}